name: Release

on:
  push:
    branches:
      - main  # o reemplace 'main' con 'master' si ese es el nombre de su rama principal

jobs:
  new-release:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        extensions: mbstring, dom
        tools: composer:v2

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - uses: actions/checkout@v3 # Checkout our working repository 
    - name: Conventional Changelog Action
      id: changelog 
      uses: TriPSs/conventional-changelog-action@v3 
      with: 
        github-token: ${{ secrets.GITHUB_TOKEN }} 
        output-file: "false" 

    - name: Create Release # This action will create the actual release 
      uses: actions/create-release@v1 
      if: ${{ steps.changelog.outputs.skipped == 'false' }} 
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with: 
        tag_name: ${{ steps.changelog.outputs.tag }}
        release_name: ${{ steps.changelog.outputs.tag }}
        body: |
          Changes in this Release
          ${{ steps.changelog.outputs.clean_changelog }}
        draft: false
        prerelease: false