name: Release

on:
  push:
    branches:
      - main  # o reemplace 'main' con 'master' si ese es el nombre de su rama principal

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        extensions: mbstring, dom
        tools: composer:v2

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Get changes
      id: changes
      run: |
        changes=$(git log --pretty=format:"- %s" $(git describe --tags --abbrev=0)..HEAD)
        changes="${changes//'%'/'%25'}"
        changes="${changes//$'\n'/'%0A'}"
        changes="${changes//$'\r'/'%0D'}"
        echo "::set-output name=changes::$changes"

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: Extract tag name
      shell: bash
      run: echo "##[set-output name=tag;]$(echo ${GITHUB_REF#refs/tags/})"
      id: extract_tag

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.extract_tag.outputs.tag }}
        release_name: Release ${{ steps.extract_tag.outputs.tag }}
        body: |
          Changes in this Release
          ${{ steps.changes.outputs.changes }}
        draft: false
        prerelease: false